connman: Autospec creation for update from version 1.37 to version 1.38
Daniel Wagner (76):
      service: Group online functions
      client: Pass error code to all D-Bus callbacks
      client: Gracefully enable/disable technologies error messages
      service: Annotate case statement with fall through
      vpn: Annotate case statement with fall through
      service: Refactor __connman_service_nameserver_append
      resolver: Don't export domain or nameserver duplicates
      config: Add support matching on device name for provisioning
      gsupplicant: Add support for setting BSS expiration age
      AUTHORS: Mention Nicola and Yasser's contributions
      vpn-provider: Do not add unsupported configuration
      openvpn: Add --tls-auth option
      service: Replace GTimeVal with GDateTime
      tools: Replace GTimeVal with GDateTime
      plugins/ethernet: Use stpncpy() instead of strcpy() for interface names
      include: Remove unused definition
      shared: Remove netlink code
      vpn: Remove Host check in plugins
      vpn: Add provider only on success to hash table
      build: Test for libmnl independent of nftables
      vpn: Add WireGuard plugin placeholder
      shared: Add Generic Netlink helpers for libmnl
      vpn: Add embeddable WireGuard library
      vpn: Introduce VPN_FLAG_NO_DAEMON
      doc: Document WireGuard VPN plugin
      vpn: Add WireGuard support
      util: Add timestamp helpers
      service: Remove GDateTime API usage
      wifi: Replace GDateVal API usage
      tools: Remove GDateTime API usage
      AUTHORS: Mention Matt and David's contributions
      wireguard: Fix use after free
      wireguard: Initialize data structure properly
      wireguard: Fix typo in option parser
      Revert "timeserver: Reload nameservers when service nameservers change"
      vpn: Use correct format specifier for size_t
      client: Prefix VPN serives identifiers with "vpn_"
      wireguard: Add PersistentKeepalive config option
      doc: Mention new PersistentKeepalive option
      doc: Add missing WireGuard to Type field
      wireguard: Make the ListenPort optional
      vpn: Call disconnect() also for non TUN VPNs
      firewall-nftables: Use nftnl_{chain|rule}_set_str() for string attributes
      service: Store configuration in empty keyfile
      ipconfig: Refactor keyfile store and load operations
      storage: Remove unused __connman_storage_open_service()
      ipconfig: Remove unused __connman_ipconfig_clear_address()
      ipconfig: Do not clear ipaddress for fixed and manual configurations
      gitignore: Ignore TAGS and cscope files
      iwd: Parse SupportedModes from adapter proxy
      iwd: Update device object
      iwd: Add KnownNetwork support
      iwd: Add KnownNetwork property to struct iwd_network
      iwd: Add Station API support
      iwd: Add AccessPoint API support
      iwd: Re-add update_signal_strenght()
      iwd: Hookup manual scan trigger
      iwd: Add support for tethering
      iwd: Disconnect from network via station API
      wireguard: Set listen port flag in device flags
      wireguard: Add PresharedKey feature
      iwd: Disable iwd's auto connect feature
      iwd: Fix station_property_changed() connected network handling
      vpn-provider: Split nameserver string also by comma
      wireguard: Add WireGuard.DNS feature
      AUTHORS: Mention David's contributions
      inet: Append correct attribute type for RTA_DST
      vpn: Remove unused type member
      wireguard: Clear plugin data pointer on disconnect
      iwd: Propogate invalid key on connection attempt failure
      ipconfig: Use prefix in store_{set|get}_int()
      iwd: Propagete signal strength values
      mnlg: Define NETLINK socket options
      test: Update all Python script to version 3
      coding-style: Update M8 about g_malloc use
      vpn: Split nameservers strings correctly

David Llewellyn-Jones (3):
      vpn-agent: Allow control of VPN credential storage/retrieval
      doc: Document VPN agent credential storage/retrieval options
      vpn-provider: Interpret VPN route ProtocolFamily as number

David Weidenkopf (3):
      iwd: Translate iwd security type
      iwd: Update signal strengths on all networks
      iwd: Transform signal strength from iwd range to ConnMan range

Henrik Persson (1):
      wifi: Verify that wifi->network is not null before using

Joakim Lotsengård (1):
      dhcp: Bind to interface when sending

John Keeping (1):
      wispr: Prevent use-after-free from agent browser request

Julien Massot (1):
      wifi: Reduce background scanning threshold from -45 to -65

Jussi Laakkonen (75):
      vpn: Let previous connection to finish before starting new one
      vpn: Set provider state to disconnect if driver has no disconnect impl
      vpn: Disconnect via provider when transport is gone or not valid
      service: Re-add run_vpn_auto_connect() with increasing delays to main loop
      service: Indicate service state when autoconnect succeeds
      service: Remove existing VPN auto connect from main loop
      service: Implement a do_auto_connect() to include VPNs in autoconnect
      service: Call vpn_auto_connect() when default service changes
      vpn: Follow coding style M12 in enum switch and fix debug log msg
      plugins: Build dynamically loadable VPN plugins
      vpn: Rename openconnect-script to vpn-script
      vpn: Move settings from main.c to vpn-settings.c
      vpn: Add support for configurable DAC privileges in settings
      task: Add support for a custom setup function
      vpn: Run VPN plugin binaries with configurable DAC privileges
      man: Document DAC privilege configuration in VPN configuration file
      dnsproxy: Remove DNS servers of disconnected/idle service
      vpn-provider: Add support for plugin specific data
      vpn-provider: Check D-Bus message arg type in set_property()
      vpn-provider: Add function to get immutable state of provider string
      vpnc: Check for D-Bus arg types in notify
      vpnc: Implement VPN agent support
      vpnc: Detect authentication and connection errors
      vpn-agent: Implement generic D-Bus error checker for plugins
      vpn-provider: React to different error types in connect_cb()
      l2tp: Use vpn-agent.c error processing for VPN agent errors
      openconnect: Use vpn-agent.c error processing for VPN agent errors
      pptp: Use vpn-agent.c error processing for VPN agent errors
      vpnc: Use vpn-agent.c error processing for VPN agent errors
      service: Implement function to set service autoconnect value
      provider: Implement function to set VPN service autoconnect value
      error: Implement OperationCanceled error type
      vpn: Handle OperationCanceled D-Bus message reply
      service: Prevent sending D-Bus error reply twice with hidden networks
      agent: Always set driver for queued message
      vpnc: Implement disconnect function to cancel queued VPN agent msg
      vpn-provider: Implement simple connection and auth error counters
      vpn-agent: Implement function to add auth failures to VPN agent msg
      doc: Add VpnAgent.AuthFailure to VPN agent API documentation
      vpn-provider: Implement setting string to bool conversion function
      openconnect: Rewrite plugin to support more auth methods and protocols
      openconnect: Use interactive mode when input to stdin is required
      doc: Add new OpenConnect PKCS parameters to VPN agent API
      doc: Add new OpenConnect configuration options to VPN config format
      TODO: Add task for libopenconnect use in OpenConnect VPN plugin
      pptp: Cancel queued VPN agent msg when disconnected
      vpnc: Inform VPN agent about authentication errors
      l2tp: Cancel queued VPN agent msg when disconnected
      l2tp: Inform VPN agent about authentication errors
      l2tp: Add default value for 'ipsec saref' to be able to use 'lock' with pppd
      vpnc: Set to use C locale prior to running the task
      l2tp: Save 'exclusive' config value in lns default context
      l2tp: Unset password as hidden value to avoid property changed signal
      vpn-provider: Change provider in failure state to idle when saving
      vpn-provider: Reply to connect request only once
      vpn: Restrict connection requests to one per connection
      provider: Handle -EALREADY in __connman_provider_connect()
      service: Clear VPN error and state if AutoConnect is set on
      vpn-agent: Implement VPN agent setting to keep credentials
      doc: Add KeepCredentials documentation to VPN agent API
      vpn-provider: Expose __vpn_provider_get_ident() to plugins
      vpn-provider: Add function to add errors without state change
      vpn-provider: Handle ENOENT in connect_cb
      openvpn: Rewrite plugin to support VPN agent and encrypted private keys
      doc: Add VPN agent API documentation for OpenVPN.PrivateKeyPassword
      pptp: Inform VPN agent about auth errors and unset pwd as hidden value
      openvpn: Use correct error value in VPN agent credential reply
      vpn-provider: Save configuration only when a property value is changed
      vpn-provider: Implement setting of multiple VPN properties with one call
      doc: Describe property array use with VPN connection SetProperty D-Bus method
      vpn-provider: Use property name "Properties" to indicate a dict
      doc: Mention "Properties" as SetProperty prop name in VPN connection API
      error: Handle EPERM as PermissionDenied D-Bus error
      openvpn: Ensure complete VPN provider state transition when disconnecting
      openvpn: Disable connection retry attempts when TCP is used as transport

Marcel Holtmann (1):
      Release 1.38

Marcus Folkesson (1):
      vpn-provider: Make reset_error_counters() static

Matt Vogt (1):
      vpn-agent: Present l2tp/pptp password input requests correctly

Mickael GARDET (2):
      tethering: Fix use after free
      gresolv: Fix ASAN runtime error

Nicola Lunghi (1):
      gweb: Fix segfault with musl

Robert Tiemann (1):
      service: Start online check on IP address update

Santtu Lakkala (2):
      inet: Add connman_inet_compare_ipv6_subnet()
      connection: Fix connections to local VPN servers

Slava Monich (1):
      rtnl: Allow watch callback to remove itself

Torstein Husebø (1):
      treewide: Fix typos

Vivien Henriet (1):
      timeserver: Reload nameservers when service nameservers change

Yasser (1):
      timezone: Fix handling of empty subpath in find_origin()

n.chaprana@samsung.com (1):
      wifi: Dereference after free in sta_remove_callback()